[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft","kubejs","productivebees","productivetrees","immersiveengineering","mekanism","create","enderio","industrialforegoing","pneumaticcraft","replication","bigreactors","megacells","refiendstorage","ae2","extendedae","advanced_ae","actuallyadditions","utilitarian","powah","moremekanismprocessing","oritech","extradisks","extrastorage","bno"]
