#General settings
[general]
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true
	#modpackProjectID is now deprecated and will be removed soon
	# Default: 0
	# Range: > 0
	modpackProjectID = 1189722
	#The name of the modpack
	modpackName = "TechAcademy"
	#The version of the modpack
	modpackVersion = "0.9.8"
