#General configuration options.
[General]
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = ["minecraft","kubejs","productivebees","productivetrees","immersiveengineering","mekanism","create","enderio","industrialforegoing","pneumaticcraft","replication","bigreactors","megacells","refiendstorage","ae2","extendedae","advanced_ae","actuallyadditions","utilitarian","powah","moremekanismprocessing","oritech","extradisks","extrastorage","bno"]
	#If enabled, any tags in the cucumber-tags.json file set to items that don't exist will be refreshed if possible.
	autoRefreshTagOptions = true
